version: '3.7'

services:

  nodejs:
    container_name: to-do-app
    image: node:14-buster-slim
    ports:
      - "3000:3000"
    working_dir: /home/node/app
    volumes:
      - ./src:/home/node/app
    command: "npm run dev"

  
